version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/expense-tracker
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=expense-tracker

volumes:
  mongodb_data:
